#include <efitypes.h>
#include <efiprotocols.h>

#ifndef EFIFS_H_
#define EFIFS_H_

#define EFI_FILE_MODE_CREATE 0x00
#define EFI_FILE_MODE_READ 0x01
#define EFI_FILE_MODE_WRITE 0x02

#define EFI_FILE_READ_ONLY 0x01
#define EFI_FILE_HIDDEN 0x02
#define EFI_FILE_SYSTEM 0x04
#define EFI_FILE_RESERVED 0x08
#define EFI_FILE_DIRECTORY 0x10
#define EFI_FILE_ARCHIVE 0x20
#define EFI_FILE_VALID_ATTR 0x37

#define EFI_FILE_PROTOCOL_REVISION 0x00010000
#define EFI_FILE_PROTOCOL_REVISION2 0x00020000

typedef EFI_STATUS(EFIAPI* EFI_FILE_OPEN)(IN EFI_FILE_PROTOCOL* This,
	OUT EFI_FILE_PROTOCOL** NewHandle, IN CHAR16* FileName,
	IN UINT64 OpenMode, IN UINT64 Attributes);

typedef EFI_STATUS(EFIAPI* EFI_FILE_CLOSE)(IN EFI_FILE_PROTOCOL* This);

typedef struct
{
	UINT64 Revision;
	EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME OpenVolume;
} EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;

typedef EFI_STATUS(EFIAPI* EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME)(
	IN EFI_SIMPLE_FILE_SYSTEM_PROTOCOL* This, OUT EFI_FILE_PROTOCOL);

#endif
